# -*- coding: utf-8 -*-
"""Practice python program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14iSh8Pn4NVGYiB0EnvGuZg4y_ySgSUpE
"""

#print grades based on marks
score=int(input("enter your grade: "))

if score>=90:
    print("grade is A")
elif score>=80 and score<90:
    print("grade is B")
elif score>=70 and score<80:
    print("grade is C")
elif score>=60 and score<70:
    print("grade is D")
elif score<60 :
    print("grade is F")
else:
    print("low grade")
